### ISSUE TITLE
Deprecating media type?

### ISSUE THREAD

**Issue by sdatspun2** [ietf-wg-httpapi/rfc7807bis#16]
>Note that because extensions are effectively put into a namespace by the problem type, it is not possible to define new "standard" members without defining a new media type

@mnot Pardon my ignorance here...what was the reason to tie "standard" members with a media type and not with schema (at least for JSON and XML)? It locks the definition but it also makes it extremely difficult to evolve. Should this be revisited? 

It would be much easier to resolve #6 and #8 if we could made backward-compatible changes to schemas.

**Comment by mnot** [comment]
The media type advertises that the content is of a certain format; if you make backwards-compatible changes to that, you're going to break some processors.

**Comment by mnot** [comment]
Is there something actionable here, or can we close this?

**Comment by dret** [comment]
i am still struggling with this a little. i am assuming this actually talks about forward-compatible changes, i.e. an updated format processed by old processors. i am not sure what the title of this issue refers to looking at the comments, though. but it seems that following the usual practice of not making "breaking changes" should be fine, right? this means not changing any definitions of the existing members, and only adding members that can be safely ignored.

**Comment by mnot** [comment]
Sorry, I should have typed backwards _in_compatible changes. Compatible changes are fine.

**Comment by mnot** [comment]
So, can we close?
