### ISSUE TITLE
provide guidance for intentionally non-dereferencable URIs

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/rfc7807bis#21]
#11 provides good guidance in terms of probably bets avoiding relative URIs. what about also providing guidance for people who intentionally want to use non-dereferencable URIs for `type` or `instance`? should we add some guidance for this as well? we had some discussion around `tag` URIs in #11 and there are other possibilities as well. but the main question is: if somebody never intends to use dereferencable URIs for `type` or `instance`, should we mention that and provide guidance?

**Comment by mnot** [comment]
Is this a duplicate of #13?

**Comment by pimterry** [comment]
I think this is indeed a duplicate

**Comment by mnot** [comment]
Closing for now; if there's a reason to distinguish it we can reopen.
