### ISSUE TITLE
Requiring a specification document

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/rfc7807bis#34]
Currently:

> A Designated Expert reviews and approves registration requests, as per {{RFC8126, Section 4.5}}. A specification document is appreciated, but not required.

That doesn't seem like a recipe for good interop. While it doesn't need to be an RFC, _some_ sort of reference is necessary...

**Comment by asbjornu** [comment]
I'm sorry, but I don't quite understand what is being referred to here. Is the quoted paragraph from RFC7807? Because I can't find it. Without more context I also don't quote understand what it is referring to.

**Comment by dret** [comment]
@asbjornu: https://ietf-wg-httpapi.github.io/rfc7807bis/draft-ietf-httpapi-rfc7807bis.html#name-registered-problem-types
