### ISSUE TITLE
Deprecate XML?

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/rfc7807bis#4]
Just asking.

**Comment by sazzer** [comment]
Is there any real harm in keeping XML in? And in the cases where the happy path of an API is using XML - they do still exist :) - then having the unhappy paths also using XML is hugely convenient, rather than needing to parse success vs failure in different ways.

**Comment by mnot** [comment]
Seems like we can close this with no action, then. If anyone wants to fight for it, we can reopen.
