### ISSUE TITLE
To do so

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/rfc7807bis#61]
3.1.1:

>  Non-resolvable URIs ought not be used when there is some future
  possibility that it might become desirable to do so.

To this non-native speaker, "to do so" points nowhere (well, actually
to using them, but that is a paradox then).
What is probably meant is:

>  Non-resolvable URIs ought not be used when there is some future
  possibility that it might become desirable to be able to resolve
  the URIs.

**Comment by benbucksch** [comment]
agreed that the proposed wording is clearer.
