### ISSUE TITLE
Avoid a default "type"

### ISSUE THREAD

**Issue by benbucksch** [ietf-wg-httpapi/rfc7807bis#65]
Remove: `When this member is not present, its value is assumed to be ["about:blank"](about:blank).`

Rationale: This would **require** (!) conforming clients to lump all non-typed errors together into one error type. Better to leave this unspecced and allow the client to make sense of it.

**Comment by dret** [comment]
On 2022-11-07 06:19, Ben Bucksch wrote:
> Remove: |When this member is not present, its value is assumed to be 
> ["about:blank"](about:blank).|
> 
> Rationale: This would *require* (!) conforming clients to lump all 
> non-typed errors together into one error. Better to leave this unspecced 
> and allow the client to make sense of it.

this may fall victim to compatibility considerations. RFC 7807 defines 
about:blank as being a "default error": 
https://www.rfc-editor.org/rfc/rfc7807#section-4.2

if we introduce a second "default" (not about:blank but the one where 
the type is absent) then that introduces the questions how these two 
defaults relate. it seems to be simpler to just keep the one default 
that we have and that we cannot take away.

**Comment by mnot** [comment]
We can't change this without changing the media type, and it's too late to do that. Closing.
