### ISSUE TITLE
Should `instance` be deprecated? 

### ISSUE THREAD

**Issue by sdatspun2** [ietf-wg-httpapi/rfc7807bis#9]
In order to solve the multiple problems use case #6, potential schema change for the Problem Details Object would include an array of problems. In cases where there is singular problem, one can respond with having a single entry in the array. In that case, should we deprecate `instance` member?

If we do deprecate, how should we handle the deprecation? Should we use the `Deprecation` response header field?

**Comment by asbjornu** [comment]
Most problems will still be single-instance, so the top-level `instance` alongside the other defined properties should be kept as is, imho. Since all properties are optional, they can be omitted if the default single-instance problem scenario doesn't fit the specific error situation.

**Comment by mnot** [comment]
Agreed with @asbjornu. I think this issue is premature; let's figure out how to handle multiple problems first. @sdatspun2 do you mind if we close it, reopening if necessary later?

**Comment by sdatspun2** [comment]
@mnot I am ok to close now.
